services:
  frontend:
    image: pasanranasinghe/gems-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: pasanranasinghe/gems-backend:latest
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=2570
      - DB_NAME=gems
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 2570
      MYSQL_DATABASE: gems
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mariadb_data:


networks:
  app-network:
    driver: bridge
